name = "Rad Pack"
author = "Aero"
version = "1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8105c93d26ea2d3b2c1dd845fd3965ec0b9642d40450ffbc4a12ac9b8409c12e"

[versions]
forge = "43.2.10"
minecraft = "1.19.2"
