name = "Rad Pack"
author = "Aero"
version = "1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2c421a5183afc84a72071c901a54eb2ef6930ff6249c8a4966520d1e9a8da5dd"

[versions]
forge = "43.2.10"
minecraft = "1.19.2"
